.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "Z" "1" "May 2018" "" ""
.
.SH "NAME"
\fBz\fR \- jump around
.
.SH "Name"
z \- jump around: port of rupa\'s z
.
.SH "SYNOPSIS"
\fBz [\-cehlprt] regex1 regex2\.\.\.\fR
.
.br
\fBzo [\-cehlprt] regex1 regex2\.\.\.\fR
.
.SH "DESCRIPTION"
Port of rupa\'s z:
.
.P
Tracks your most used directories, based on \'frecency\'\. The data is stored in a file located at \fB$Z_DATA\fR\.
.
.P
After a short learning phase, z will take you to the most \'frecent\' directory that matches ALL of the regexes given on the command line, in order\.
.
.P
For more details about frecency, see https://github\.com/rupa/z\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR, \fB\-\-clean\fR
Removes directories that no longer exist from \fB$Z_DATA\fR\.
.
.TP
\fB\-e\fR, \fB\-\-echo\fR
Prints the best match\. No cd\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a brief help message\.
.
.TP
\fB\-l\fR, \fB\-\-list\fR
Show a list of matches, and their scores\. No cd\.
.
.TP
\fB\-r\fR, \fB\-\-rank\fR
Match by rank only\.
.
.TP
\fB\-t\fR, \fB\-\-recent\fR
Match by recent only\.
.
.TP
\fB\-x\fR, \fB\-\-delete\fR
Removes the current directory from \fB$Z_DATA\fR\.
.
.SH "EXAMPLES"
.
.TP
\fBz foo\fR
Goes to directory best matching \fBfoo\fR\.
.
.TP
\fBzo foo\fR
Opens file manager of directory best matching \fBfoo\fR\.
.
.TP
\fBz \-t foo\fR
Goes to most recent directory matching \fBfoo\fR\.
.
.TP
\fBz \-x\fR
Removes the current directory from \fB$Z_DATA\fR\.
.
.SH "CONFIGURATION"
.
.TP
\fBset \-U Z_CMD "j"\fR
Change commands to \fBj\fR and \fBjo\fR
.
.TP
\fBset \-U Z_DATA "$HOME/\.foo"\fR
Set data file to \fB$HOME/\.foo\fR
.
.TP
\fBset \-U ZO_METHOD "opencmd"\fR
Runs \fBopencmd dir\fR on \fBzo dir\fR (defaults to \fBopen\fR or \fBxdg\-open\fR)
.
.TP
\fBset \-U Z_OWNER "username"\fR
Ensure data file is owned by \fBusername\fR\. This prevents usage of \fBz\fR with \fBsudo\fR to cause file to be inaccessible in non\-sudo sessions\.

