.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "June 2016" "" ""
\fBz\fR is a fish port of z \fIhttp://github\.com/rupa/z\fR\.
.
.P
\fBz\fR tracks the directories you visit\. With a combination of frequency and recency, it enables you to jump to the directory in mind\.
.
.P
A \fIpure\-fish\fR port means it is \fIfast\fR and \fIfish\-friendly\fR, with tab\-completions and lazy\-loading\. Top that off with greater customizability and a small amount of added functionality\.
.
.SH "Install"
.
.SS "fish >=2\.3\.0"
With fisherman \fIhttps://github\.com/fisherman/fisherman\fR
.
.IP "" 4
.
.nf

fisher z
.
.fi
.
.IP "" 0
.
.SS "fish <2\.3\.0"
If you can\'t upgrade your build, append the following code to your \fB~/\.config/fish/config\.fish\fR\.
.
.IP "" 4
.
.nf

for file in ~/\.config/fish/conf\.d/*\.fish
    source $file
end
.
.fi
.
.IP "" 0
.
.P
Or let me do that for you\.
.
.IP "" 4
.
.nf

curl \-L git\.io/snippet >> ~/\.config/fish/config\.fish
.
.fi
.
.IP "" 0
.
.SH "Usage"
.
.nf

z [\-c \-\-clean]       Cleans out Z_DATA
z [\-e \-\-echo] foo    Prints best match, no cd
z [\-l \-\-list] foo    List matches, no cd
z [\-r \-\-rank] foo    Searches by rank, cd
z [\-t \-\-recent] foo  Searches by recency, cd
z [ \-h \-\-help]       Print this help
zo foo               Opens file manager for best match
.
.fi
.
.SH "Examples"
.
.nf

z foo             Goes to directory best matching foo
zo foo            Opens file manager of directory best matching foo
z \-t foo          Goes to most recent directory matching foo
.
.fi
.
.SH "Configuring Z"
There are commands that let you modify the behaviour of \fBz\fR:
.
.IP "" 4
.
.nf

set \-U Z_CMD "j"               Change commands to j and jo
set \-U Z_DATA "$HOME/\.foo"     Set data file to $HOME/\.foo
set \-U ZO_METHOD "opencmd"     Runs `opencmd dir` on `zo dir` (defaults to `open` or `xdg\-open`)
.
.fi
.
.IP "" 0

